In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('Louisville_Metro_KY_-_Crime_Data_2021.csv', low_memory=False)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72123 entries, 0 to 72122
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   INCIDENT_NUMBER  72123 non-null  object
 1   DATE_REPORTED    72123 non-null  object
 2   DATE_OCCURED     72123 non-null  object
 3   BADGE_ID         72121 non-null  object
 4   CRIME_TYPE       72123 non-null  object
 5   UOR_DESC         72123 non-null  object
 6   NIBRS_CODE       72123 non-null  object
 7   UCR_HIERARCHY    69811 non-null  object
 8   ATT_COMP         72050 non-null  object
 9   LMPD_DIVISION    72123 non-null  object
 10  LMPD_BEAT        72117 non-null  object
 11  PREMISE_TYPE     72114 non-null  object
 12  BLOCK_ADDRESS    72123 non-null  object
 13  City             72112 non-null  object
 14  ZIP_CODE         72098 non-null  float64
 15  ObjectId         72123 non-null  int64
dtypes: float64(1), int64(1), object(14)
memory usage: 8.8+ MB

In [5]:
df.head()

,INCIDENT_NUMBER,DATE_REPORTED,DATE_OCCURED,BADGE_ID,CRIME_TYPE,UOR_DESC,NIBRS_CODE,UCR_HIERARCHY,ATT_COMP,LMPD_DIVISION,LMPD_BEAT,PREMISE_TYPE,BLOCK_ADDRESS,City,ZIP_CODE,ObjectId
0,80-20-077625,2021/01/01 04:10:00,2020/12/31 20:00:00,8403,VANDALISM,CRIMINAL MISCHIEF - 1ST DEGREE,290,PART II,COMPLETED,6TH DIVISION,613,RESIDENCE / HOME,4100 BLOCK ST FRANCIS LN ...,LOUISVILLE,40218.0,1
1,80-20-077625,2021/01/01 04:10:00,2020/12/31 20:00:00,8403,BURGLARY,BURGLARY - 2ND DEGREE,220,PART I,COMPLETED,6TH DIVISION,613,RESIDENCE / HOME,4100 BLOCK ST FRANCIS LN ...,LOUISVILLE,40218.0,2
2,80-21-000003,2021/01/01 00:03:00,2021/01/01 00:03:00,7939,ASSAULT,ASSAULT - 1ST DEGREE,13A,PART I,COMPLETED,1ST DIVISION,112,HIGHWAY / ROAD / ALLEY,600 BLOCK S 18TH ST ...,LOUISVILLE,40203.0,3
3,80-21-000005,2021/01/01 00:14:00,2021/01/01 00:13:00,5293,ASSAULT,WANTON ENDANGERMENT-1ST DEGREE,13A,PART I,COMPLETED,3RD DIVISION,323,RESIDENCE / HOME,800 BLOCK CANDLEGLOW CT ...,LOUISVILLE,40214.0,4
4,80-21-000006,2021/01/01 00:03:00,2020/12/31 23:03:00,5258,VANDALISM,CRIMINAL MISCHIEF - 1ST DEGREE,290,PART II,COMPLETED,4TH DIVISION,424,DEPARTMENT / DISCOUNT STORE,3200 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215.0,5

In [6]:
ndf = df.drop(columns=['ATT_COMP', 'UCR_HIERARCHY', 'NIBRS_CODE', 'LMPD_BEAT','ObjectId', 'BADGE_ID'])

In [7]:
ndf.head()

,INCIDENT_NUMBER,DATE_REPORTED,DATE_OCCURED,CRIME_TYPE,UOR_DESC,LMPD_DIVISION,PREMISE_TYPE,BLOCK_ADDRESS,City,ZIP_CODE
0,80-20-077625,2021/01/01 04:10:00,2020/12/31 20:00:00,VANDALISM,CRIMINAL MISCHIEF - 1ST DEGREE,6TH DIVISION,RESIDENCE / HOME,4100 BLOCK ST FRANCIS LN ...,LOUISVILLE,40218.0
1,80-20-077625,2021/01/01 04:10:00,2020/12/31 20:00:00,BURGLARY,BURGLARY - 2ND DEGREE,6TH DIVISION,RESIDENCE / HOME,4100 BLOCK ST FRANCIS LN ...,LOUISVILLE,40218.0
2,80-21-000003,2021/01/01 00:03:00,2021/01/01 00:03:00,ASSAULT,ASSAULT - 1ST DEGREE,1ST DIVISION,HIGHWAY / ROAD / ALLEY,600 BLOCK S 18TH ST ...,LOUISVILLE,40203.0
3,80-21-000005,2021/01/01 00:14:00,2021/01/01 00:13:00,ASSAULT,WANTON ENDANGERMENT-1ST DEGREE,3RD DIVISION,RESIDENCE / HOME,800 BLOCK CANDLEGLOW CT ...,LOUISVILLE,40214.0
4,80-21-000006,2021/01/01 00:03:00,2020/12/31 23:03:00,VANDALISM,CRIMINAL MISCHIEF - 1ST DEGREE,4TH DIVISION,DEPARTMENT / DISCOUNT STORE,3200 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215.0

In [8]:
ndf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72123 entries, 0 to 72122
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   INCIDENT_NUMBER  72123 non-null  object
 1   DATE_REPORTED    72123 non-null  object
 2   DATE_OCCURED     72123 non-null  object
 3   CRIME_TYPE       72123 non-null  object
 4   UOR_DESC         72123 non-null  object
 5   LMPD_DIVISION    72123 non-null  object
 6   PREMISE_TYPE     72114 non-null  object
 7   BLOCK_ADDRESS    72123 non-null  object
 8   City             72112 non-null  object
 9   ZIP_CODE         72098 non-null  float64
dtypes: float64(1), object(9)
memory usage: 5.5+ MB

In [9]:

ndf['ZIP_CODE'] = ndf['ZIP_CODE'].fillna(0)

In [10]:
ndf['ZIP_CODE'] = ndf['ZIP_CODE'].astype(int)

In [11]:
ndf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72123 entries, 0 to 72122
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   INCIDENT_NUMBER  72123 non-null  object
 1   DATE_REPORTED    72123 non-null  object
 2   DATE_OCCURED     72123 non-null  object
 3   CRIME_TYPE       72123 non-null  object
 4   UOR_DESC         72123 non-null  object
 5   LMPD_DIVISION    72123 non-null  object
 6   PREMISE_TYPE     72114 non-null  object
 7   BLOCK_ADDRESS    72123 non-null  object
 8   City             72112 non-null  object
 9   ZIP_CODE         72123 non-null  int64
dtypes: int64(1), object(9)
memory usage: 5.5+ MB

In [12]:
ndf.head()

,INCIDENT_NUMBER,DATE_REPORTED,DATE_OCCURED,CRIME_TYPE,UOR_DESC,LMPD_DIVISION,PREMISE_TYPE,BLOCK_ADDRESS,City,ZIP_CODE
0,80-20-077625,2021/01/01 04:10:00,2020/12/31 20:00:00,VANDALISM,CRIMINAL MISCHIEF - 1ST DEGREE,6TH DIVISION,RESIDENCE / HOME,4100 BLOCK ST FRANCIS LN ...,LOUISVILLE,40218
1,80-20-077625,2021/01/01 04:10:00,2020/12/31 20:00:00,BURGLARY,BURGLARY - 2ND DEGREE,6TH DIVISION,RESIDENCE / HOME,4100 BLOCK ST FRANCIS LN ...,LOUISVILLE,40218
2,80-21-000003,2021/01/01 00:03:00,2021/01/01 00:03:00,ASSAULT,ASSAULT - 1ST DEGREE,1ST DIVISION,HIGHWAY / ROAD / ALLEY,600 BLOCK S 18TH ST ...,LOUISVILLE,40203
3,80-21-000005,2021/01/01 00:14:00,2021/01/01 00:13:00,ASSAULT,WANTON ENDANGERMENT-1ST DEGREE,3RD DIVISION,RESIDENCE / HOME,800 BLOCK CANDLEGLOW CT ...,LOUISVILLE,40214
4,80-21-000006,2021/01/01 00:03:00,2020/12/31 23:03:00,VANDALISM,CRIMINAL MISCHIEF - 1ST DEGREE,4TH DIVISION,DEPARTMENT / DISCOUNT STORE,3200 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215

In [13]:
ndf['DATE_REPORTED'] = pd.to_datetime(ndf['DATE_REPORTED'])
ndf['DATE_OCCURED'] = pd.to_datetime(ndf['DATE_OCCURED'])
ndf.info()
ndf.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72123 entries, 0 to 72122
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   INCIDENT_NUMBER  72123 non-null  object
 1   DATE_REPORTED    72123 non-null  datetime64[ns]
 2   DATE_OCCURED     72123 non-null  datetime64[ns]
 3   CRIME_TYPE       72123 non-null  object
 4   UOR_DESC         72123 non-null  object
 5   LMPD_DIVISION    72123 non-null  object
 6   PREMISE_TYPE     72114 non-null  object
 7   BLOCK_ADDRESS    72123 non-null  object
 8   City             72112 non-null  object
 9   ZIP_CODE         72123 non-null  int64
dtypes: datetime64[ns](2), int64(1), object(7)
memory usage: 5.5+ MB

,INCIDENT_NUMBER,DATE_REPORTED,DATE_OCCURED,CRIME_TYPE,UOR_DESC,LMPD_DIVISION,PREMISE_TYPE,BLOCK_ADDRESS,City,ZIP_CODE
0,80-20-077625,2021-01-01 04:10:00,2020-12-31 20:00:00,VANDALISM,CRIMINAL MISCHIEF - 1ST DEGREE,6TH DIVISION,RESIDENCE / HOME,4100 BLOCK ST FRANCIS LN ...,LOUISVILLE,40218
1,80-20-077625,2021-01-01 04:10:00,2020-12-31 20:00:00,BURGLARY,BURGLARY - 2ND DEGREE,6TH DIVISION,RESIDENCE / HOME,4100 BLOCK ST FRANCIS LN ...,LOUISVILLE,40218
2,80-21-000003,2021-01-01 00:03:00,2021-01-01 00:03:00,ASSAULT,ASSAULT - 1ST DEGREE,1ST DIVISION,HIGHWAY / ROAD / ALLEY,600 BLOCK S 18TH ST ...,LOUISVILLE,40203
3,80-21-000005,2021-01-01 00:14:00,2021-01-01 00:13:00,ASSAULT,WANTON ENDANGERMENT-1ST DEGREE,3RD DIVISION,RESIDENCE / HOME,800 BLOCK CANDLEGLOW CT ...,LOUISVILLE,40214
4,80-21-000006,2021-01-01 00:03:00,2020-12-31 23:03:00,VANDALISM,CRIMINAL MISCHIEF - 1ST DEGREE,4TH DIVISION,DEPARTMENT / DISCOUNT STORE,3200 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215

In [14]:
ndf = ndf.drop(columns=['INCIDENT_NUMBER'])

In [15]:
ndf.head()

,DATE_REPORTED,DATE_OCCURED,CRIME_TYPE,UOR_DESC,LMPD_DIVISION,PREMISE_TYPE,BLOCK_ADDRESS,City,ZIP_CODE
0,2021-01-01 04:10:00,2020-12-31 20:00:00,VANDALISM,CRIMINAL MISCHIEF - 1ST DEGREE,6TH DIVISION,RESIDENCE / HOME,4100 BLOCK ST FRANCIS LN ...,LOUISVILLE,40218
1,2021-01-01 04:10:00,2020-12-31 20:00:00,BURGLARY,BURGLARY - 2ND DEGREE,6TH DIVISION,RESIDENCE / HOME,4100 BLOCK ST FRANCIS LN ...,LOUISVILLE,40218
2,2021-01-01 00:03:00,2021-01-01 00:03:00,ASSAULT,ASSAULT - 1ST DEGREE,1ST DIVISION,HIGHWAY / ROAD / ALLEY,600 BLOCK S 18TH ST ...,LOUISVILLE,40203
3,2021-01-01 00:14:00,2021-01-01 00:13:00,ASSAULT,WANTON ENDANGERMENT-1ST DEGREE,3RD DIVISION,RESIDENCE / HOME,800 BLOCK CANDLEGLOW CT ...,LOUISVILLE,40214
4,2021-01-01 00:03:00,2020-12-31 23:03:00,VANDALISM,CRIMINAL MISCHIEF - 1ST DEGREE,4TH DIVISION,DEPARTMENT / DISCOUNT STORE,3200 BLOCK TAYLOR BLVD ...,LOUISVILLE,40215

In [16]:
# ndf.to_csv('Clean_Louisville_Metro_KY_-_Crime_Data_2021.csv')

In [25]:
len(ndf['CRIME_TYPE'])

72123

In [1]:
# ndf.plot(x="ZIP_CODE", y=[len("CRIME_TYPE")], kind="bar")
# plt.show()
ndf.plot(kind = 'bar', x = 'QUANTITY', y = 'SALES')

NameError: name 'lures' is not defined